### ISSUE TITLE
It seems no console on V500.R001.A103.00.G021.B013

### ISSUE THREAD

**Issue by theverdu** [duhow/wibox#14]
Hi duhow,
Thanks for your work on this :-) my goal is to integrate my wibox on HA, but It seems there is no console access on newer firmware versions, nothing appear after init process:

![image](https://user-images.githubusercontent.com/93820609/200171094-ab49bac8-2aa9-4e39-b882-f6ab41ac1b7b.png)

I can access to U-Boot pressing any key on start, any tip on how to proceed at this point?

For other users: to avoid soldering i filed 2mm this connectors with a dremel:

![image](https://user-images.githubusercontent.com/93820609/200171406-a743bd9a-7056-4409-9446-eb38927a74d7.png)

**Comment by Co1dSUN** [comment]
Hello,
I have done the same just a couple weeks ago. You have to change tty in
u-boot. But I forgot which tty it should be. It has to be one of ttySGK0,
ttySGK1 or ttySGK2
------
Best regards / S pozdravem / С наилучшими пожеланиями,
Krivopishin Yaroslav.

**Comment by theverdu** [comment]
Wow Co1dSUN, many thanks for your fast response,

`setenv consoledev 'ttySGK0'`
`saveenv`
`reset`

As you say, this makes the login appear when i hit any key, but can't log with the usr/pw provided, it say "user no valid" and continuous message are appearing, do you know if i must disable any output or do something else?

![image](https://user-images.githubusercontent.com/93820609/200174682-486dceff-7804-4bcc-9ac5-0af9e8bb0669.png)

**Comment by Co1dSUN** [comment]
IDK, I used console only to realize where I do something wrong and why it is not start any more or to upload firmware by u-boot again and again. What firmware version do you have there? You can check it in wibox app.

**Comment by duhow** [comment]
Thanks for the info @theverdu !
The output you're looking at comes from the **Sofia** application, not a direct shell.
You can try with `adminapp/adminapp2` or `root/aszeno` ?
I'd be very interested in a full dump of the **mtd** partitions if you get the chance to have them.

**Comment by theverdu** [comment]
Thanks duhow, root/aszeno works for me. Telnet console is not enabled by default and adding the env telnetctrl=1 does not enable it on restart.

But finally i got the mdt0-6 files, i send you by pm and try to continue from there.

Many thanks for your help

**Comment by duhow** [comment]
Got the files, while I'll still need to do more investigation:

mtd2 - 1966080 `3f630e56a3d31066a38409edac19ab37`
Linux kernel ARM boot executable zImage (little-endian)

mtd3 - 2293760 `5b9d494a882869f44b340d1a8f18f418`
Squashfs filesystem, little endian, version 4.0, xz compressed, 2227342 bytes, 505 inodes, blocksize: 65536 bytes, created: Sun May 22 06:43:56 2022
md5 of 2227342 bytes - `6bc7e845c4fd5afeffa5d1a873c39e9e`

mtd4 - 11599872 `d56c6b9d948f4216efcdb590cec25ce3`
Linux Compressed ROM File System data, little endian size 4235264 version 2 sorted_dirs CRC 0x10606cc5, edition 0, 1756 blocks, 105 files
md5 of 4235264 bytes - `b496b8018bf2029a9458893f0f14dd13`

- `/usr/run.sh` now has `#telnetd &` commented / disabled. Thanks. 😂  (the `env telnetctrl=1` is used in other HiSilicon cameras, but does not apply in here)
- New addition to kernel network settings:
```sh
echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore
echo 2 > /proc/sys/net/ipv4/conf/all/arp_announce
```
- I see some references in `config.lua` and Sofia binary: `SupportAmazonAlexa = 0`

**Comment by duhow** [comment]
Overall I don't see any differences in the procedure, so you may proceed to install the patch as defined in the guide.

**Comment by duhow** [comment]
Due to a bad re-soldering process I did, apparently I've cut RX pin, so now I have an isolated board. 🥲 
I face some issues with B013, if Sofia does not run (that triggers some other process?), the board will stop the Wifi.
`RTL871X: CardDisableRTL8188FU`.

Currently investigating this. Any feedback is welcome :)

**Comment by duhow** [comment]
Found the issue...
Sofia won't load Wifi settings from a normal `wpa_supplicant.conf` file, and if the file does not exist in `/mnt/mtd/wpa_supplicant.conf`, then the board won't connect to the Wireless AP, which explains all the other behaviors. I'll add more details and fixes for this.

**Comment by duhow** [comment]
Added https://github.com/duhow/wibox/commit/bbfdfad5c5dfb525b49717c7a00d6a216b2285b6 .
Since we already found how to get the console access and so, I'm resolving this issue.
