### ISSUE TITLE
Source links in docs seems to be not available

### ISSUE THREAD

**Issue by XavierVal** [duhow/wibox#2]
The links in the doc are down
https://linuch.pl/blog/fermax-wayfi-wideodomofon-hack-czesc-1

https://linuch.pl/blog/fermax-wayfi-wideodomofon-hack-czesc-2

https://linuch.pl/blog/fermax-wayfi-wideodomofon-hack-czesc-3

Regards!

**Comment by XavierVal** [comment]
workaround: 
https://webcache.googleusercontent.com/search?q=cache:YmReKkaRoDgJ:https://linuch.pl/blog/fermax-wayfi-wideodomofon-hack-czesc-1+&cd=1&hl=es&ct=clnk&gl=es

**Comment by duhow** [comment]
Back again.
