### ISSUE TITLE
Wi-box serial connection

### ISSUE THREAD

**Issue by DanivosYoun** [duhow/wibox#20]
Hi duhow,

I try to serial connection because of newest firmware,

but when, I connect serial connection it did not prompt any linux login prompt,

can you check what can I do?

![KakaoTalk_Photo_2024-03-29-01-05-58](https://github.com/duhow/wibox/assets/76880527/cf449078-5d87-4755-ad67-fefbbbff3fb4)

**Comment by duhow** [comment]
See message `Hit Enter key to stop autoboot`. From there, you can enter `uboot` menu.
Check [Recovery via U-Boot](https://github.com/duhow/wibox/blob/main/INSTALL.md#recovery-via-u-boot) for more details.
