### ISSUE TITLE
Difficulties getting serial access

### ISSUE THREAD

**Issue by gtrabanco** [duhow/wibox#24]
Wi-Box Firmware: V500.R001.A103.00.G0021.B013
Computer OS: MacOS/Raspbian

### Board power supply

I have connected positive (red) and negative (brown) of the board to external Power Supply of 18V.

![IMG_3196 Pequeño](https://github.com/duhow/wibox/assets/1969593/7818ed20-d49c-433d-8089-99d7e47c6427)

I could get the board in Wi-Box app and connect it to my wifi.

I have done this because I am not in the flat where the board will be located.

### Board serial access

I have soldered the cables as expected.

![IMG_3197 Pequeño](https://github.com/duhow/wibox/assets/1969593/f8ab9e4b-bcda-4f39-9f6e-489614811c97)

And linked the cables manually using same "port" on wage connectors to make sure they are getting contact. Because I had no black I used Green dupont cable. and they are linked as you can see here.

![IMG_3199 Pequeño](https://github.com/duhow/wibox/assets/1969593/be60fe26-2d58-4d0c-9c44-29a15b785e07)

I have connected GND (yellow) to GND, TX (black that ends in green) to RX and RX (red) to TX.

![IMG_3198 Pequeño](https://github.com/duhow/wibox/assets/1969593/37ea9ef2-688f-4c29-93a1-91fc62371b23)

## Accessing

I connected usb and it is accesible through `/dev/ttyUSB0` in a raspberry but I also checked on macOS which is accesible through `/dev/cu.usbserial-1420`. I will give this value as `$PHYSICAL_PORT` var in the connection command.

I tried to connect using picocom on raspbian and tried with screen in macOS and Linux:

```shell
sudo -v # prompt for sudo password
sudo screen $PHYSICAL_PORT 115200
```

And with all this done just provide me a good black screen if I try to use the serial connection after the board got power on (and connected to my wifi) but if I connected first the USB and later power on provides me on the screen `@@@H@` sometimes.

## Other information

The board has opened 4 ports:

```
PORT      STATE SERVICE
80/tcp    open  http
443/tcp   open  https
6683/tcp  open  unknown
34567/tcp open  dhanalakshmi
```

If I browse `http://wibox-ip` or `https` provides a 404 not found. Sometimes this is used to provision the wpa_supplicant at start configuration but remains open after configuring the wifi.

**Comment by duhow** [comment]
You should get at least serial messages from u-boot (when powering on the board). 
If you don't, check the solder, and your USB/TTL adapter (permissions, speed to baud-rate 115200)

After u-boot, if you don't get any messages, check https://github.com/duhow/wibox/issues/14#issuecomment-1304806472 .

I will update this into docs shortly.

**Comment by sairon** [comment]
> I have connected positive (red) and negative (brown) of the board to external Power Supply of 18V.

Is the ground of the USB-TTL converter also connected to the ground of the external power supply? It can't work if the potentials are different.
